server:
  port: 8091
  max-http-header-size: 48000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdb
    username: postgres
    password: postgres
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


sftp:
  server:
    url: localhost
    user: test
    password: test123